name: Release & Publish Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  version_or_release:
    if: github.event_name == 'push'
    name: Version or Create Release PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Create release pull request or apply version
        uses: changesets/action@v1
        with:
          version: npx changeset version
          commit: "ci: apply version bump"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_changeset_release:
    if: github.ref_type == 'branch' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: version_or_release

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Create GitHub Release from Changesets
        run: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_publish:
    if: github.event_name == 'release'
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fastify-static-server:latest
            ${{ secrets.DOCKER_USERNAME }}/fastify-static-server:${{ github.ref_name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
