name: Release & Publish Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  maybe_create_release_pr:
    if: github.event_name == 'push'
    name: Create release PR if there are changesets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci

      - name: Check for changesets
        id: changeset_check
        run: |
          if [ -z "$(ls .changeset 2>/dev/null)" ]; then
            echo "has_changesets=false" >> $GITHUB_OUTPUT
          else
            echo "has_changesets=true" >> $GITHUB_OUTPUT
          fi

      - name: Create release pull request
        if: steps.changeset_check.outputs.has_changesets == 'true'
        uses: changesets/action@v1
        with:
          version: npx changeset version
          commit: "ci: apply version bump"
          createGithubReleases: true
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_publish:
    if: github.event_name == 'release'
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from GitHub release tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fastify-static-server:latest
            ${{ secrets.DOCKER_USERNAME }}/fastify-static-server:${{ env.VERSION }}
